# Generated by Django 6.0.3 on 2026-03-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='bairro',
            field=models.CharField(default='padrao', max_length=100, verbose_name='Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrega',
            name='numero',
            field=models.CharField(default=0, max_length=10, verbose_name='Número'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrega',
            name='ponto_referencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entrega',
            name='rua',
            field=models.CharField(default='padrao', max_length=200, verbose_name='Rua da Entrega'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrega',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
