# Generated by Django 6.0.3 on 2026-03-18 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0002_alter_veiculo_filial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='motorista_atual',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='motorista',
            field=models.ForeignKey(blank=True, limit_choices_to={'perfil': 'entregador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculos', to=settings.AUTH_USER_MODEL),
        ),
    ]
