# Generated by Django 6.0.3 on 2026-03-21 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0002_entrega_bairro_entrega_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entregas.filial', verbose_name='Filial Padrão'),
        ),
    ]
