# Generated by Django 6.0.3 on 2026-03-18 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0003_remove_veiculo_motorista_atual_veiculo_motorista'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entregas.veiculo'),
        ),
    ]
